version: '3'
services:
  master_db:
    container_name: master
    image: mysql:latest
    restart: always
    env_file: 
      - ./env/master.env
    volumes:
      - ./data/master:/var/lib/mysql
      - ./config/master_config.cnf:/etc/mysql/conf.d/my.cnf
      - ./setup-master.sh:/docker-entrypoint-initdb.d/setup-master.sh
      - ./shared:/shared  # Include the shared volume for the slave as well
    ports:
      - "3306:3306"
    networks:
      - mysql_network

  slave1_db:
    container_name: slave1
    image: mysql:latest
    restart: always
    env_file: 
      - ./env/slave.env
    volumes:
      - ./data/slave1:/var/lib/mysql
      - ./config/slave_config1.cnf:/etc/mysql/conf.d/my.cnf
      - ./setup-slave.sh:/docker-entrypoint-initdb.d/setup-slave.sh
      - ./shared:/shared  # Include the shared volume for the slave as well
    ports:
      - "3308:3306"  # Redirecting host port 3308 to container port 3306

    depends_on:
      - master_db
    networks:
      - mysql_network

  slave2_db:
    container_name: slave2
    image: mysql:latest
    restart: always
    env_file: 
      - ./env/slave.env
    volumes:
      - ./data/slave2:/var/lib/mysql
      - ./config/slave_config2.cnf:/etc/mysql/conf.d/my.cnf
      - ./setup-slave.sh:/docker-entrypoint-initdb.d/setup-slave.sh
      - ./shared:/shared  # Include the shared volume for the slave as well
    ports:
      - "3309:3306"  # Redirecting host port 3309 to container port 3306
    depends_on:
      - master_db
    networks:
      - mysql_network
volumes:
  shared:
    driver_opts:
      type: none
      device: ${PWD}/shared
      o: bind
      permissions: "rw"
networks:
  mysql_network:
    driver: bridge